### ISSUE TITLE
Should batteries negative's be linked to the GND PIN or not ?

### ISSUE THREAD

**Issue by fitaine** [hackaninstant/Servo-Shutter#1]
Hi,
I downloaded the gerber file and ordered a pcb but I have a hard time knowing what to do. I don't want to make mistake as it could be dangerous.

My wondering is why isn't there any connection to both of the negatives of the batteries ? Positives are linked to the VIN pin. **Should negatives be linked to the GND PIN or not ?**

-

Also, to make my future device rechargeable by mini USB I bought two TP4506 to place between lipo batteries and the PCB. I'll adjust the voltage for the servo with a mini DC/DC voltage regulator. I'll try to hook all stuff on one battery, see if it works, because it annoys me to have to recharge nano and servo separately. I'll keep you noted !

**Comment by hackaninstant** [comment]
The schematic shows both negative battery terminals connect to the GND pin. One positive battery terminal connects to the VIN pin on the board and the other to the VIN on the servo, which isolates the servo from the Arduino. You could possibly connect a capacitor to the servo to help smooth out the servo action and use just one battery.
