### ISSUE TITLE
Display is messed up

### ISSUE THREAD

**Issue by fitaine** [hackaninstant/Servo-Shutter#2]
Hi, I'm having trouble on the software side it seems:

When I first loaded the shutter.ino, the display seemed bricked, but navigations worked fine (buttons and rotary). I then loaded some examples from the SSD 1306Ascii and the results were the same. I tried some examples from adafruit to check if that was a problem from the display and it worked fine.

Have you experience any display issues in the making ?
1 - Loaded with SSD 1306 Ascii example
![IMAGE 2024-09-15 12:18:52](https://github.com/user-attachments/assets/4d624f24-b27d-4aa3-9703-832d73991e32)

2 - Loaded with Adafruit 1306 example
![IMAGE 2024-09-15 12:20:06](https://github.com/user-attachments/assets/d63ee5dd-1e5e-40eb-be10-73f9712b63c8)

Any idea where it come from ?

**Comment by fitaine** [comment]
I got a response from Greiman on the [SSD1306Ascii Github page](https://github.com/greiman/SSD1306Ascii/issues/122) saying: 
"Looks like the display controller for this module is a 12864. It claims to be 1306 compatible but I must use some command that is not handled by the 12864.

I am only doing minimal maintenance on this library so don't plan to add features or support new controllers."

Would help tell me what screen you bought so I'm sure it works ?

**Comment by hackaninstant** [comment]
Ok, thanks for the heads up. I'll mark this closed if you'd like to open this issue on Greiman's SSC1306Ascii page.
